package edu.kit.ipd.pp.joframes.ast.acha;

import edu.kit.ipd.pp.joframes.ast.base.Rule;

/**
 * Collection of methods generated by the regular expression and super type rules, represented as a rule.
 * 
 * @author Martin Armbruster
 */
public class MethodCollector extends Rule {
}
